openapi: 3.1.0
info:
  title: "Content Delivery Network"
  description: "This is a CDN"
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /images:
    get:
      description: "Get all images"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"

components:
  schemas: { }